"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import WorkItem, WorkItemCreate, WorkItemUpdate
from .store import store

app = FastAPI(
    title="Field Service Work Orders API",
    version="0.1.0",
    description="REST API for Field Service Work Orders. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "work-items", "description": "The work items the field team acts on."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/work-items", response_model=List[WorkItem], tags=["work-items"])
def list_work_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/work-items", response_model=WorkItem, status_code=201, tags=["work-items"])
def create_work_item(body: WorkItemCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/work-items/{item_id}", response_model=WorkItem, tags=["work-items"])
def get_work_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Work item not found")
    return item


@app.patch("/api/work-items/{item_id}", response_model=WorkItem, tags=["work-items"])
def update_work_item(item_id: int, body: WorkItemUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Work item not found")
    return item


@app.delete("/api/work-items/{item_id}", status_code=204, tags=["work-items"])
def delete_work_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Work item not found")
